
import Model.SanPham;
import Model.SanPham_service;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import utility.ShareHelper1;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class SanPham1 extends javax.swing.JFrame{
     private final SanPham_service dao = new SanPham_service();
     private View_SP p = new View_SP();
    DefaultTableModel mol = new DefaultTableModel();
    int index = 0;
    /**
     * Creates new form SanPham
     */
    public SanPham1()  {
        initComponents();
        init();
        mol = (DefaultTableModel) tbl_Sp2.getModel();
        Load();
    }
    
    void Load() {
        mol.setRowCount(0);
        ArrayList<Model.SanPham> lst = dao.getAll();
        for (Model.SanPham sp : lst) {
            mol.addRow(new Object[]{sp.getMaSp(), sp.getTenSp(), sp.getMoTa(), sp.getMaCC(), sp.getSolg(), sp.getDonGia(), sp.getNgayNhap(), sp.getAnh(), sp.gettrangThai()});
        }
    }
    Void setModel(int index) {
        SanPham sp = dao.getAll().get(index);
//        txt_.setText(sp.getTenSp());
//        txt_loai.setText(sp.getLoai());
//        txt_mnhaynhap.setText(String.valueOf(sp.getNgayNhap()));
//        txt_mota.setText(sp.getMoTa());
//        txt_ncc.setText(sp.getMaCC());
//        txt_solg.setText(String.valueOf(sp.getSolg()));
//        lbl_anh.setToolTipText(sp.getAnh());
         return null;
    }
    
    private void init() {
        this.setLocationRelativeTo(null);
        setIconImage(ShareHelper1.APP_ICON);
        new Timer(10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat formater = new SimpleDateFormat("hh::mm:ss a");
                String text = formater.format(now);
                lbl_timer.setText(text);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Sp2 = new javax.swing.JTable();
        lbl_timer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_Sp2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Sp", "Tên Sp", "Mô Tả", "Nhà cung cấp", "Số lượng", "Đơn giá", "Ngày nhập", "Ảnh", "Trạng thái"
            }
        ));
        tbl_Sp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_Sp2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Sp2);

        lbl_timer.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(628, Short.MAX_VALUE)
                .addComponent(lbl_timer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(289, Short.MAX_VALUE)
                .addComponent(lbl_timer)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_Sp2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_Sp2MouseClicked
//        index = tbl_Sp2.getSelectedRow();
//        tabs.setSelectedIndex(1);
//        setModel(index);
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_Sp2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SanPham1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SanPham1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SanPham1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SanPham1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SanPham1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_timer;
    private javax.swing.JTable tbl_Sp2;
    // End of variables declaration//GEN-END:variables
}
